### PR TITLE
Added home button in the nav bar

### LINKED ISSUE #80: Adding a home button to go to index.html instead of using "Kitabe" to go to home.
**Describe the bug**
Clicking on Kitabe will direct you to the index page is not easily understood. Users are in a habit of using Home button. So to go to the home page they always look for the home button.

**Expected behavior**
A home button in the right where rest of the buttons are will be more user friendly.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I am a GsSOC'21 participant.

### PR DESCRIPTION
**Pull request by kanishka8276**
## Description
- List out your changes
Added home button in the navbar.
- Link the Issue which this resolves
#80

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

Screenshot (71)
Screenshot (72)
Screenshot (74)

### CODE REVIEW

**Review by maneprajakta — APPROVED** [review]
Good to Go.

**Comment by maneprajakta** [comment]
Update PR template with ss.

**Comment by kanishka8276** [comment]
@maneprajakta @Praful932  Done!!

**Comment by Praful932** [comment]
@kanishka8276 For some reason, github isn't showing the deployed PR, here's the URL
https://kitabe-pipeline-pr-102.herokuapp.com/

**Comment by kanishka8276** [comment]
> @kanishka8276 For some reason, github isn't showing the deployed PR, here's the URL
> https://kitabe-pipeline-pr-102.herokuapp.com/

It's working fine.

**Review by Praful932 — CHANGES_REQUESTED** [review]

**Comment by kanishka8276** [comment]
@Praful932 done!

**Review by Praful932 — APPROVED** [review]
Nice work 🚀

**Pull request merged**
