### PR TITLE
Enhanced navbar icons

### LINKED ISSUE #137: Tooltip & Icon Fix
**Is your feature request related to a problem? Please describe.**
The navbar icons can be made to look better and also the login/signup form.

**Describe the solution you'd like**
The icons in the navbar look bigger and not appealing to the user.Also,the signin signup pages can be made more attractive.It has a lot of vacant space which can be used to add relevant images or inspire the user to actually make an account on our platform.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
I would like to work on this issue and create more user appealing UI along with form restructuring.

### PR DESCRIPTION
**Pull request by Sristi27**
## Description
- Added Tooltips to Navbar Icons
- Fixes #137 

## Affected Dependencies
NA

## How has this been tested?
Tested on my local machine

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA
Screenshot 2021-04-06 at 1 15 41 AM

## GIF After
Screenshot 2021-04-06 at 1 15 24 AM

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by Praful932 — CHANGES_REQUESTED** [review]
Unstage `settings.py`

**Comment by Sristi27** [comment]
> Unstage `settings.py`

Okay.

**Comment by Sristi27** [comment]
Done!

**Comment by maneprajakta** [comment]
@Praful932 if you could deploy this PR.

**Comment by Praful932** [comment]
Seems like github is facing some [issues](https://www.githubstatus.com/)

**Comment by maneprajakta** [comment]
@sonaljain067 can you share a gif or video for `360x640` px and large screen here.

**Comment by Sristi27** [comment]
> @Sristi27 can you share a gif or video for `360x640` px and large screen here

https://user-images.githubusercontent.com/53037053/114129526-55a5df00-991c-11eb-9647-dea2c7ee7248.mov

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- For small screen, we don't need icons keep it same as on the website.

**Comment by maneprajakta** [comment]
@Sristi27 also your update your fork it's behind the master.

**Comment by Sristi27** [comment]
> @Sristi27 also your update your fork it's behind the master.
Done

**Comment by Praful932** [comment]
Hi @Sristi27, could you update your master, there was some issue with auto deploy of PRs which was fixed rn, now we can view your changes online :)

**Comment by Sristi27** [comment]
Currently it is on issueSristi branch..do you want me to update the master on the forked one?

**Comment by Praful932** [comment]
Yea my bad, update this branch with latest commits from master

**Comment by Sristi27** [comment]
@Praful932 Do check once now

**Review by Praful932 — CHANGES_REQUESTED** [review]
1. image
Not all the icons have tooltips
2. image
And some of the tooltips are note centered
3. For mobile view it should be same as earlier with names

**Comment by maneprajakta** [comment]
@Sristi27 any updates?

**Comment by maneprajakta** [comment]
Closing because of inactiveness.

**Pull request closed without merging**
