### PR TITLE
Login/signup toggle functionality 

### PR DESCRIPTION
**Pull request by Inventor77**
## Changes Made 
- SearchBar shifted to Left and Broaden a bit
- Added a search Icon in Searchbar 
- Changed the size of Home, Explore, Login and Signup Icons 
- changed the login color 
- made a Signup Btn

## Affected Dependencies
- Layout.html
- Layout.css

## GIF Before
Screenshot (590)

## GIF After
Screenshot (589)

## Checklist
- [ Y ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ Y ] My changes do not edit/add any not required files.
- [ Y ] My changes are covered by tests.

### CODE REVIEW

**Comment by Inventor77** [comment]
@Praful932 Sir its my First Time to Create WIP PR please guide me did I have done something wrong or how con I improve more

**Comment by Inventor77** [comment]
@Praful932 Also Sir I'm trying to Achieve the Attached Animation for Signup and Login page. To achieve this I have to merge two Signup.html and login.html files in one and so their CSS file too. But I'm getting some errors when I'm  doing that. I'm fully Devoted towards this but don't know why I always facing a failure

Togglingpage

**Comment by Praful932** [comment]
@Inventor77 The navbar looks better in the earlier version, there is already an issue for navbar enhancement.
Your issue is for the login/signup toggle, if there is anything else you want to do about the navbar let us know. We would like the theme to be maintained for the website, and the animation you showed doesn't.

**Comment by Inventor77** [comment]
> 
> 
> @Inventor77 The navbar looks better in the earlier version, there is already an issue for navbar enhancement.
> Your issue is for the login/signup toggle, if there is anything else you want to do about the navbar let us know. We would like the theme to be maintained for the website, and the animation you showed doesn't.

Sir then their is no need to add this Animation for signup and login page right

**Comment by Praful932** [comment]
> > @Inventor77 The navbar looks better in the earlier version, there is already an issue for navbar enhancement.
> > Your issue is for the login/signup toggle, if there is anything else you want to do about the navbar let us know. We would like the theme to be maintained for the website, and the animation you showed doesn't.
> 
> Sir then their is no need to add this Animation for signup and login page right

That's what you made the issue for tho right?
You can :) but first we would like a mockup from your side regarding the same, after approval start coding

**Comment by Inventor77** [comment]
@Praful932 Navbar  is not for me and also This toggling Animation doesn't match with Theme. Sir then I will reach you soon by some NEW UI for Signup and Login

**Comment by Inventor77** [comment]
> 
> 
> > > @Inventor77 The navbar looks better in the earlier version, there is already an issue for navbar enhancement.
> > > Your issue is for the login/signup toggle, if there is anything else you want to do about the navbar let us know. We would like the theme to be maintained for the website, and the animation you showed doesn't.
> > 
> > 
> > Sir then their is no need to add this Animation for signup and login page right
> 
> That's what you made the issue for tho right?
> You can :) but first we would like a mockup from your side regarding the same, after approval start coding

Thanks alot sir for being patience :)

**Comment by Inventor77** [comment]
> 
> 
> > @Inventor77 The navbar looks better in the earlier version, there is already an issue for navbar enhancement.
> > Your issue is for the login/signup toggle, if there is anything else you want to do about the navbar let us know. We would like the theme to be maintained for the website, and the animation you showed doesn't.
> 
> Sir then their is no need to add this Animation for signup and login page right

Also sir would I change something in Navbar you would like because I have already worked on it please let it not get wasted

**Comment by Praful932** [comment]
@Inventor77 It's not about code going to waste or not. It's about the usability and how it fits into the project. If you see the starter guide, we have explicitly mentioned that for **UI/UX changes we appreciate design mockups first, after our approval/changes the contributor starts to code**, This makes sure that there's no wastage of energy/time on both sides :) Agree?

**Comment by Inventor77** [comment]
> @Inventor77 It's not about code going to waste or not. It's about the usability and how it fits into the project. If you see the starter guide, we have explicitly mentioned that for **UI/UX changes we appreciate design mockups first, after our approval/changes the contributor starts to code**, This makes sure that there's no wastage of energy/time on both sides :) Agree?
> 

Yes Sir, Now I will share Login and Signup Mockup first

**Review by Praful932 — CHANGES_REQUESTED** [review]
There seems to be a conflict, take care of that

**Comment by maneprajakta** [comment]
@Inventor77 any updates?

**Comment by Inventor77** [comment]
> @Inventor77 any updates?

Mam Please lend me some time, my semester end exam is going on

**Comment by maneprajakta** [comment]
> > @Inventor77 any updates?
> 
> Mam Please lend me some time, my semester end exam is going on

Yep No issues.

**Comment by maneprajakta** [comment]
@Inventor77 We are closing this now you can create a fresh PR when you are done.

**Pull request closed without merging**
