### PR TITLE
Enhancing Typeface

### LINKED ISSUE #149: Enhacing typeface
**Is your feature request related to a problem? Please describe.**
On the login and sign-up page, more than 3 types of font-styles are used which don't look professional and consistent.

**Describe the solution you'd like**
Changing the fonts to a type of font that would be looking consistent and premium look. For example, adding 2 or a maximum of 3 fonts that would be a little similar to one another like a Helvetica, Frutiger, and Arial font could make it more appealing to users.  But now it doesn't look much appealing and readable as different font-styles like different forms of cursive and Arial fonts are used on a single page.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**

**Additional context**
Before
Screenshot from 2021-04-02 17-15-55

After
Screenshot from 2021-04-01 14-41-00

### PR DESCRIPTION
**Pull request by sonaljain067**
## Description
- Changed typeface of login and signup page
- Fixes #149 

## Affected Dependencies
NA

## How has this been tested?
Using `flake8`, `python manage.py test`.
No test fails.

## GIF Before
typeface-before

## GIF After
typeface-after

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [X] My changes do not edit/add any unrequired files.
- [X] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Check small screen for both pages.
Screenshot from 2021-04-07 09-51-58

**Comment by sonaljain067** [comment]
> * Check small screen for both pages.
>   Screenshot from 2021-04-07 09-51-58

Mam, what changes I have to make?

**Comment by maneprajakta** [comment]
> > * Check small screen for both pages.
> >   Screenshot from 2021-04-07 09-51-58
> 
> Mam, what changes I have to make?

Ya the button seems to be coming out of form border if you could handle this for small screen on both pages.

**Comment by sonaljain067** [comment]
> > > * Check small screen for both pages.
> > >   Screenshot from 2021-04-07 09-51-58
> > 
> > 
> > Mam, what changes I have to make?
> 
> Ya the button seems to be coming out of form border if you could handle this for small screen on both pages.

Sure mam!

**Review by Praful932 — CHANGES_REQUESTED** [review]
@sonaljain067 I would recommend keeping the font and weight of the **form placeholders** as it is, it can confuse the user whether it is already filled
image
Also add some space between the google icon and the text

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- For signup page button is still not inside form border.
- For login page the button is not aligned to the center.

**Comment by sonaljain067** [comment]
Ok, I would modify it.

**Comment by maneprajakta** [comment]
@sonaljain067 
- Can you attach gif of both pages for screen `360x640`px and large screen here.

**Comment by sonaljain067** [comment]
> @sonaljain067
> 
> * Can you attach gif of both pages for screen `360x640`px and large screen here.

Sure!

**Comment by sonaljain067** [comment]
typeface-after
login-after-small

**Comment by sonaljain067** [comment]
signup-after-small

**Comment by Praful932** [comment]
Hi @sonaljain067 , could you update your master, there was some issue with auto deploy of PRs which was fixed rn, now we can view your changes online :)

**Comment by sonaljain067** [comment]
I am unable to understand what changes I have to make.

**Comment by Praful932** [comment]
@sonaljain067 check out fork faq in [starter guide](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by maneprajakta** [comment]
> I am unable to understand what changes I have to make.

You can reach out to us on discord if still not clear.

**Comment by sonaljain067** [comment]
Got it!

**Comment by sonaljain067** [comment]
Is it appropriate?

**Comment by Praful932** [comment]
@sonaljain067 I believe you should keep the original case for the sign up/in buttons

**Comment by sonaljain067** [comment]
Ok.

**Review by maneprajakta — APPROVED** [review]

**Review by Praful932 — APPROVED** [review]
Nice work 🚀

**Pull request merged**
