### PR TITLE
Added Customized Scrollbar

### LINKED ISSUE #169: Customized Scrollbar
**Is your feature request related to a problem? Please describe.**

Currently, the scrollbar doesn't go well with the background of the webpages.

**Describe the solution you'd like**

I would like to customize the scrollbar by changing it's color according to the background of the webpage (All Pages).

**Are you willing to contribute to this issue?** [Yes/No]

`Yes`

**Additional context**

**Before**

Screenshot_1

**After**
Screenshot_2

As per your suggestion I can change the width/color of the scrollbar as well.

Kindly assign me this issue under GSSoC'21

### PR DESCRIPTION
**Pull request by Saatvik21**
## Description
- As the title of this PR suggests, I added a custom scrollbar which matches the background and theme of the project.
- Fixes #169 

## Affected Dependencies
- Layout.css

## How has this been tested?
- I've tested this using `flake8`, `python manage.py test` and it shows 0 errors.

## Video Before
https://imgur.com/KSjyANv

## Video After (Can't upload more than 30 secs video here , so pasting a link for the same)
https://imgur.com/a/CsS938y

## Alternatives Considered 

https://user-images.githubusercontent.com/61618767/113402816-504c1000-93c3-11eb-9aa1-20383fdfd52f.mp4

Should I add a Hover Effect (shown in above video) over the scrollbar as well?

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by Praful932 — COMMENTED** [review]
@maneprajakta If we keep scrollbar of the same color, it isn't really visible. We should it make it darker or any other theme Wdyt
image

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Also check responsiveness is maintained

**Comment by maneprajakta** [comment]
@Praful932 what you think about this:
Screenshot from 2021-04-02 15-25-38

**Comment by Saatvik21** [comment]
@maneprajakta I'll do the required changes after @Praful932 agrees with your suggested color , also should I add a hover effect which will change the color of the scrollbar to #f86751 on hover?

**Comment by Praful932** [comment]
> @Praful932 what you think about this:
> Screenshot from 2021-04-02 15-25-38

Seems fine in the image

**Comment by maneprajakta** [comment]
> @maneprajakta I'll do the required changes after @Praful932 agrees with your suggested color , also should I add a hover effect which will change the color of the scrollbar to #f86751 on hover?

Yep go for it.

**Comment by Saatvik21** [comment]
> > @maneprajakta I'll do the required changes after @Praful932 agrees with your suggested color , also should I add a hover effect which will change the color of the scrollbar to #f86751 on hover?
> 
> Yep go for it.

Done! Lemme know if there are still some changes to do.

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- check for small screen nav bar needs to be handled.
Screenshot from 2021-04-03 14-25-06

**Review by maneprajakta — APPROVED** [review]

**Review by Praful932 — APPROVED** [review]
Nice work 🚀

**Pull request merged**
