### PR TITLE
Set Debug=False

### PR DESCRIPTION
**Pull request by sneha-nitdgp**
## Description
- Changed Debug=True to Debug=False

- closes [#21](https://github.com/Praful932/Kitabe/issues/89)

## How has this been tested?
Ran it in my localhost

##  Before
-  
kitabe

## After
-
kitabe 2

## Checklist
- [ ✔️] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).

- [✔️ ] My changes do not edit/add any unrequired files.
- [✔️ ] My changes are covered by tests.

### CODE REVIEW

**Comment by maneprajakta** [comment]
@sneha-nitdgp please fill PR template correctly as asked in it like :
In **Description** it should come what you changed

**Comment by sneha-nitdgp** [comment]
@maneprajakta Yes, please check it now.

**Comment by sneha-nitdgp** [comment]
@maneprajakta Yes, please check it now.

**Review by Praful932 — CHANGES_REQUESTED** [review]
@sneha-nitdgp Update the PR template with issue that it links, see other PRs :)
Also That is not the change that what was discussed in the issue discussion, please check

**Comment by sneha-nitdgp** [comment]
Updated!

**Comment by maneprajakta** [comment]
@Praful932 check this out

**Review by Praful932 — CHANGES_REQUESTED** [review]
We need the DEBUG = False in development
That's why I mentioned in the issue comments,
> you can add this line DEBUG = False in the condition

[here](https://github.com/Praful932/Kitabe/blob/master/BookRecSystem/settings.py#L190)

**Pull request closed without merging**
