### PR TITLE
Frontend Bug Fixes

### LINKED ISSUE #30: Frontend Bug Fixes
**Describe the bug**
There are certain frontend bug fixes especially the **Rate this book** button after the last patch. All bugs are after a user signs in.

**Screenshots**

1. **Homepage** - Popular Among Users Section (Improper Button Size and Alignment)
image
2. **Your Read Section** (Improper Size, Alignment and Rating Validation)
image

**Expected behavior**
1. All buttons should be fixed as when user is not logged in
image
2. For 3. Validation should be added after a book is rated, similar to below
validation

**Definition of Done**
All sub-tasks are done and pass tests

### PR DESCRIPTION
**Pull request by simranbhalla3**
## Description
- Changed the size and alignment of buttons on Homepage.
- Made proper button size and alignment on explore page
- Changed the size and alignment of buttons on Your read section
- Fixes #30 

## How has this been tested?
Using given tests (flake8 , python manage.py test)
## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA
-NA

## GIF After
-NA

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [X] My changes do not edit/add any unrequired files.
- [X] My changes are covered by tests.

kitabe1
kitabe2

kitabe3

The main changes i have made are about changing and adding padding and margin to the buttons in the index.css and explore.css file

### CODE REVIEW

**Review by Praful932 — CHANGES_REQUESTED** [review]
@simranbhalla3 Awesome work 🚀, Could you edit the PR with GIFs and relevant details, then we can review

**Comment by simranbhalla3** [comment]
> @simranbhalla3 Awesome work 🚀, Could you edit the PR with GIFs and relevant details, then we can review

I have added the required details in my PR, kindly check and let me know if anything else is required. :)

**Comment by maneprajakta** [comment]
@Praful932 explore page conflict btw this and PR #120 .

**Comment by maneprajakta** [comment]
> > @simranbhalla3 Awesome work rocket, Could you edit the PR with GIFs and relevant details, then we can review
> 
> I have added the required details in my PR, kindly check and let me know if anything else is required. :)

Attach for `your read` page also.

**Comment by simranbhalla3** [comment]
> @Praful932 explore page conflict btw this and PR #120 .

Could You please explain this one? I didnt get what you were trying to convey

**Comment by maneprajakta** [comment]
> > @Praful932 explore page conflict btw this and PR #120 .
> 
> Could You please explain this one? I didnt get what you were trying to convey

@simranbhalla3, not a problem from your side we already have a PR working on explore page.So we need to figure out the merging of both PR.

**Comment by simranbhalla3** [comment]
> > > @simranbhalla3 Awesome work rocket, Could you edit the PR with GIFs and relevant details, then we can review
> > 
> > 
> > I have added the required details in my PR, kindly check and let me know if anything else is required. :)
> 
> @simranbhalla3
> Attach for `your read` page also.

Made the necessary changes. Kindly check.

**Comment by Praful932** [comment]
> > > @Praful932 explore page conflict btw this and PR #120 .
> > 
> > 
> > Could You please explain this one? I didnt get what you were trying to convey
> 
> @simranbhalla3, not a problem from your side we already have a PR working on explore page.So we need to figure out the merging of both PR.

Hi @simranbhalla3 There was a recent change in the explore page, so update your branch, and we won't be requiring the explore page fix in the PR, I have updated the description accordingly #30 
Thanks

**Comment by maneprajakta** [comment]
@simranbhalla3 any updates?

**Comment by simranbhalla3** [comment]
> @simranbhalla3 any updates?

I have made the changes , please check

**Comment by maneprajakta** [comment]
@simranbhalla3 there are conflicts 
simply [unstage](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request) explore.css

**Review by maneprajakta — CHANGES_REQUESTED** [review]
@simranbhalla3 there are conflicts 
simply [unstage](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request) explore.css

**Review by Praful932 — CHANGES_REQUESTED** [review]
Your fork is behind, please update it, the explore needed change is not required as mentioned in the issue description

**Comment by simranbhalla3** [comment]
> Your fork is behind, please update it, the explore needed change is not required as mentioned in the issue description

I am having issues unstaging the file , should i just update the explore.css with the latest code that is been uploaded?
please help.

**Comment by Praful932** [comment]
> > Your fork is behind, please update it, the explore needed change is not required as mentioned in the issue description
> 
> I am having issues unstaging the file , should i just update the explore.css with the latest code that is been uploaded?
> please help.

Check out the pinned messages on discord, and follow the steps

**Review by Praful932 — CHANGES_REQUESTED** [review]
[Unstage ](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)`settings.py` & `requirements.txt`

**Comment by simranbhalla3** [comment]
> [Unstage ](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)`settings.py` & `requirements.txt`

Done the required changes and unstaged the files please check

**Comment by maneprajakta** [comment]
@simranbhalla3 too many changes are coming from your side.
If you have updated your fork make a fresh PR with changes.

**Review by Praful932 — CHANGES_REQUESTED** [review]
@simranbhalla3 Did you ran the command that I sent earlier? Also you have to push it to your branch

**Comment by maneprajakta** [comment]
@simranbhalla3 if you have not figured it out reach out to us on discord.

**Comment by maneprajakta** [comment]
@simranbhalla3 just put on yes or no :) are you working on this?

**Comment by simranbhalla3** [comment]
> @simranbhalla3 just put on yes or no :) are you working on this?

Yes I am working

**Comment by maneprajakta** [comment]
@simranbhalla3 any updates?

**Comment by maneprajakta** [comment]
No updates recieved

**Pull request closed without merging**
