### PR TITLE
Book description wip

### PR DESCRIPTION
**Pull request by knmehta12**
## Description
- I've assigned books to an ISBN and then found their description. I don't have the process for finding ISBN in this notebook.( But I'm just using a library and I can provide that code if you want. ) 
- Link the Issue which this resolves
The books didn't have a description and now they do. I'm working towards the similarity algorithm and will soon be finished.  
- The ipynb can be found in notebooks folder

## Affected Dependencies
My work doesn't interact with the webapp yet. 

## How has this been tested?
Not sure how to answer this. Manually, I think.

## GIF Before
 NA

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ ] My changes do not edit/add any unrequired files. 
- [ ] My changes are covered by tests.

### CODE REVIEW

**Comment by Praful932** [comment]
@maneprajakta If there is a library that can give book description/summary we can replace the scraping from goodreads right, Wdyt?

**Comment by maneprajakta** [comment]
> @maneprajakta If there is a library that can give book description/summary we can replace the scraping from goodreads right, Wdyt?

Yes we can :+1:

**Comment by Praful932** [comment]
@knmehta12 Any updates?

**Comment by knmehta12** [comment]
No sir. I haven't worked on it for a while since my exams are going on. Also I just discovered that some descriptions are in other languages so their characters are Non ASCII so I'll have to fix that first then use a model. :)

**Comment by Praful932** [comment]
> No sir. I haven't worked on it for a while since my exams are going on. Also I just discovered that some descriptions are in other languages so their characters are Non ASCII so I'll have to fix that first then use a model. :)

Alright, that's fine. Good luck for your exams
Just keep us in the loop :)

**Comment by Praful932** [comment]
There seems to be two notebooks could you point to the correct one, and remove the other one

**Comment by maneprajakta** [comment]
@knmehta12 could you add the code for the part how you created the `desc.csv` file also in the same notebook.

**Comment by knmehta12** [comment]
It actually requires sending a lot of http requests so I had to do that at intervals over a period of a couple days. I have uploaded `desc.csv` file so you can just put it there and run it.

**Comment by Praful932** [comment]
I think it would be good to have something we can verify, from where did you extract the desc?

**Comment by knmehta12** [comment]
Sure I'll upload a notebook for that. I extracted these from a library isbnlib that takes data from google books. :)

**Comment by Praful932** [comment]
Alright,here are some of the things we would need
- The new dataset(with description) - as exactly as the goodbooks one except with one column added
- A notebook very similiar to [this](https://colab.research.google.com/drive/1LRr4Nm2I2HRJUTXbRea3sK5A1Bvp_lav)- preferrably google collab(a link will do, no need of uploading) - you will only need to copy paste your code into the CV section.

We will be only using the `cosine_rating_sim` file from your PR at the end and discard other files as other files are only needed for review

**Comment by Praful932** [comment]
Let us know when it's ready for review :)

**Comment by knmehta12** [comment]
Yes sure. It'll take a day or two. thank you for guiding me.

**Comment by maneprajakta** [comment]
New PR #210

**Pull request closed without merging**
