### PR TITLE
About section and resize banner images

### LINKED ISSUE #185: Adding "About" section and Resizing banner images
**Is your feature request related to a problem? Please describe.**
Users might not exactly understand what the site is about. Also, when the site loads, the banner image covers the 3/4th of the viewport. 

**Describe the solution you'd like**
1. Adding an **About** section on the Home page will help users understand what the website does/ is.
2. Resizing the height of banner images, to direct the user's attention to feature sections.
 

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
Alternatively, we can add a separate **About** page (as and when required), which describes the site's features.

### PR DESCRIPTION
**Pull request by Greeshma2903**
## Description
- Added **About** section as a banner image
- Resized and added the updated banner images
- Fixes #185 

## Affected Dependencies
NA

## How has this been tested?
`flake8`
`python manage.py test`

## GIF Before
- Before

## GIF After
after

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
check `3.webp` white space is there on top.

**Comment by Greeshma2903** [comment]
> check `3.webp` white space is there on top.

Ohkay, working on it

Should I update my local repo with the latest commits, and then push again? OR just push the changes?

**Comment by Praful932** [comment]
Yea update and push

**Review by maneprajakta — APPROVED** [review]

**Review by Praful932 — APPROVED** [review]
Nice work @Greeshma2903 🚀

**Comment by Greeshma2903** [comment]
> Nice work @Greeshma2903 🚀

Thank you!

**Comment by Praful932** [comment]
There seems to be a responsive issue could you make the banner a bit larger in responsive mode, It seems too small compared to the other elements of the application

**Comment by Greeshma2903** [comment]
> There seems to be a responsive issue could you make the banner a bit larger in responsive mode, It seems too small compared to the other elements of the application

Ohkay, working on it

**Comment by Greeshma2903** [comment]
I checked the deployment on phone, the author names are out of frame, can I correct it and push changes?

**Comment by maneprajakta** [comment]
@Greeshma2903 Yes, you can.

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Check the welcome banner it's getting cropped from sides for small screen.

**Comment by Praful932** [comment]
@maneprajakta Is it just me or has the timeout slowed out a bit?

**Comment by maneprajakta** [comment]
@Praful932 seems fine to me!

**Comment by Greeshma2903** [comment]
> * Check the welcome banner it's getting cropped from sides for small screen.

Ohkay, could you tell the approx screen size? Cause I am unable to figure out the smallest screen size for mobiles (min-width). 😅

**Comment by maneprajakta** [comment]
@Greeshma2903 check for this screen size 360x640 px

**Comment by maneprajakta** [comment]
@Greeshma2903 side designs is not coming up for welcome banner on small screen check [deployment](https://kitabe-pr-197.herokuapp.com/)

**Comment by Greeshma2903** [comment]
> @Greeshma2903 side designs is not coming up for welcome banner on small screen check [deployment](https://kitabe-pr-197.herokuapp.com/)

Considering the text is not readable on small screens, I gave `object: cover` property to the images for small screens. So for about 250- 360px, the side design wouldn't be visible(as `img` expands to fit the container).  Hope it's alright, did it just to make the text more readable. 🙂😅

So it will look like this for screens size ~360px and below 
image

**Comment by Praful932** [comment]
Looks nice, no worries

**Comment by maneprajakta** [comment]
> > @Greeshma2903 side designs is not coming up for welcome banner on small screen check [deployment](https://kitabe-pr-197.herokuapp.com/)
> 
> Considering the text is not readable on small screens, I gave `object: cover` property to the images for small screens. So for about 250- 360px, the side design wouldn't be visible(as `img` expands to fit the container). Hope it's alright, did it just to make the text more readable. 
> 
> So it will look like this for screens size ~360px and below
> image

Ok, no issues then!

**Review by maneprajakta — APPROVED** [review]
Great Work :rocket:

**Comment by Greeshma2903** [comment]
> Great Work 🚀

Thank you!

**Pull request merged**
