### PR TITLE
Book Summary Fix

### LINKED ISSUE #10: Incomplete Book Summary
**Describe the bug**
Book Summary of certain Books after searching are incomplete.

**To Reproduce**
1. Go to the [Homepage](https://kitabe-app.herokuapp.com/)
2. Click on the search bar
3. Type a Book Name
4. Let the Book Summary Load

**Expected behavior**
The book summary should be readable and complete.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 86

**Smartphone (please complete the following information):**
 - Not applicable

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Praful932**
- Fixes #10 

**Demo:**

summary-fix

### CODE REVIEW

**Review by maneprajakta — COMMENTED** [review]
Not getting much 😅

**Comment by Praful932** [comment]
@maneprajakta earlier the book summary was abrupt, Try searching the books's on the live website and see it's summary you'll know.

**Comment by maneprajakta** [comment]
I think the issue can be closed now @Praful932

**Comment by Praful932** [comment]
Are the new changes suffice?
Since now the book summary is good to go and not abrupt.

**Comment by maneprajakta** [comment]
Screenshot from 2020-12-14 15-36-14

Check this one.
If the summary exceeds a certain limit it should show such " ... " and also let the last word be complete this is what we aim at right.

**Comment by Praful932** [comment]
@maneprajakta Yes correct, I tried other variants and the latest commit one seems to work best.
image
image
image

**Comment by maneprajakta** [comment]
@Praful932 God to go :rocket: :rocket:

**Pull request merged**
