### PR TITLE
Adding book description to the already running model

### PR DESCRIPTION
**Pull request by knmehta12**
## Description
- List out your changes
I created a column named cleaned_desc in the already existing dataset and reformatted the model with an extra feature.
As directed, I uploaded a csv file with book description in it. And the link to colab notebook

## How has this been tested?
It has been tested on books of different genres and in various languages. It gives a relevant recommendations for almost all of them.

## GIF Before
N/A
## GIF After
N/A
## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by Praful932** [comment]
Directly Replace `books.csv` with the one you uploaded and there seems to be 2 extra columns at the start, [drop them](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html). It should be similar to the earlier one so we can check with the running application.

**Comment by Praful932** [comment]
Also make the notebook as same as [this](https://colab.research.google.com/drive/1LRr4Nm2I2HRJUTXbRea3sK5A1Bvp_lav#scrollTo=7WeAH1-s5HSM) one, only difference would be your implementation and the new dataset

**Comment by knmehta12** [comment]
Hello. It says I closed this?? I didn't. I was actually uploading the new dataset and colab link.

**Comment by maneprajakta** [comment]
You deleted the branch `book-desc-model` which made the PR get closed.

**Pull request closed without merging**
