### PR TITLE
Convert images from .png to .webp format

### PR DESCRIPTION
**Pull request by Greeshma2903**
## Description
- Converted .png images to .webp
- https://github.com/Praful932/Kitabe/issues/72
- Made required changes to .HTML pages wrt. image format

## Affected Dependencies
- NA

## How has this been tested?
`flake8`
`python manage.py test`

## GIF After
After-convert
After-convert-signup

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — APPROVED** [review]
Good to go :rocket:

**Comment by Praful932** [comment]
@maneprajakta Just want to confirm the quality of the images
@Greeshma2903 Could you add gifs, there's some issue with the heroku review process

**Comment by Greeshma2903** [comment]
> @maneprajakta Just want to confirm the quality of the images
> @Greeshma2903 Could you add gifs, there's some issue with the heroku review process

Yes sure

**Comment by Praful932** [comment]
Yes, just show the pages wherever the changes affect

**Comment by Greeshma2903** [comment]
> Yes, just show the pages wherever the changes affect

I have added the GIFs above

**Review by Praful932 — APPROVED** [review]

**Pull request merged**
