### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
## Description
- Added dark mode feature in the website
- #41 

## How has this been tested?
Deployed locally. 

## Screenshots when deployed in local server
Screenshot (1047)
Screenshot (1048)
Screenshot (1049)
Screenshot (1050)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by SnehaVeerakumar** [comment]
@Praful932 @maneprajakta Kindly review and leave a feedback if any.

**Comment by Praful932** [comment]
@maneprajakta It's deployed already for some reason not showing up on the PR here.
https://kitabe-pr-191.herokuapp.com/

**Review by maneprajakta — CHANGES_REQUESTED** [review]
Check this :
- The moon loads before the preloader.
-  Signup and login form both are not aligned with the side image.
- Keep the same font style for Signup and login `welcome` heading.

**Comment by SnehaVeerakumar** [comment]
> Check this :
> 
> * The moon loads before the preloader.
> * Signup and login form both are not aligned with the side image.
> * Keep the same font style for Signup and login `welcome` heading.

1st and 3rd point noted. But in 2nd point, image is not properly displaying if I try to alter that because both are specified in same class. I cannot alter the class as it will affect the display in light mode.

**Comment by SnehaVeerakumar** [comment]
Once the light mode for signup page is ready, I guess I can give a try about that alignment

**Comment by maneprajakta** [comment]
> Once the light mode for signup page is ready, I guess I can give a try about that alignment

Okay fine.
Will check that later on.

**Comment by SnehaVeerakumar** [comment]
@maneprajakta Both of the font is same !! you can check the code as well as demo.

**Comment by SnehaVeerakumar** [comment]
Dark mode button now loads after the preloader.

@maneprajakta

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Check when user logins in there are many faults.
- Check for the small screen the nav-bar is not responsive now we prefer `360-640`px.
- More details button text by default white would look better.

**Comment by SnehaVeerakumar** [comment]
> * Check when user logins in there are many faults.
> * Check for the small screen the nav-bar is not responsive now we prefer `360-640`px.
> * More details button text by default white would look better.

Kindly understand that I cannot alter responsiveness of page with dark mode. You need to change the code in light theme, which will automatically gets inherited for dark theme. Even if I wish to change code in light theme, the result is not being seen in the server.

1st and 3rd point will be rectified soon.
Thank you.

**Comment by SnehaVeerakumar** [comment]
@maneprajakta Review it now please

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- This is what I meant from responsiveness the navbar it would be same for both theme right.
Screenshot from 2021-04-19 17-28-07
- When user logs in check nav-bar.
Screenshot from 2021-04-19 17-33-23
- When user login in check `Rate this book button` it's design should be same as in home page when user is not logged in but it appears something like this on all pages
Screenshot from 2021-04-19 17-37-39
- Also reduce the size of the moon and sun a bit. 
- Keep on adding small comments in CSS file so that it would be easy for us in future.

**Comment by maneprajakta** [comment]
@SnehaVeerakumar also there are some UI bugs write know in the website which might affect your work check #30 for that.

**Comment by SnehaVeerakumar** [comment]
1. Nav bar - resolved. If I add 1 more space, it changes the alignment 
2. Rate this button after login - Doesn't have a class to call in the css file I created
3. Size of moon and sun - reduced.
4. Comments for css is not necessary as it is just changing light mode css. Only ".dark-mode" is added to each class. Every frontend developer is aware of that.
5. Login/signup page - aligned properly

@maneprajakta @Praful932

**Comment by Praful932** [comment]
The login/signup seems a bit out of alignment also can we come up with consistent font, the font seems to be different for the pages
image

**Comment by SnehaVeerakumar** [comment]
Screenshot_20210419-220147_Chrome
Screenshot_20210419-220151_Chrome

Fix the alignment in light mode, it will be changed here.
@maneprajakta

**Comment by SnehaVeerakumar** [comment]
I will rwmove the font for this. Whatever you keep in light mode will be inherited. 
@maneprajakta

**Comment by SnehaVeerakumar** [comment]
Please expect what you have in light mode. Not everything will be changed in dark mode

**Comment by SnehaVeerakumar** [comment]
That's all I can do. If you want, approve or reject. No more requirements can be satisfied as your light mode already has lots of bugs. 

@maneprajakta @Praful932

**Comment by Praful932** [comment]
There's an ongoing PR for that fix #206 , After that is fixed, we can proceed with this

**Comment by SnehaVeerakumar** [comment]
> There's an ongoing PR for that fix #206 , After that is fixed, we can proceed with this

Wow, you said it finally after 1 week of my work !!

**Comment by SnehaVeerakumar** [comment]
Screenshot_20210420-173829_Discord


Closing due to improper communication between mentor and project admin. 
Unrealistic expectation : Having same class for both forms and expecting different alignments.

**Comment by Praful932** [comment]
@SnehaVeerakumar 
Left is your dark mode and right is the current project's
So would the **alignment changes** be required in your code(This PR) or the website's page?
Is the alignment an unrealistic expectation?
It's not nice to call out admins/mentors by posting chat screenshots after calling the project and all the contributors spent their time on a mess.
image

**Comment by SnehaVeerakumar** [comment]
@Praful932  As i already said, there is no comkunication between you people. I informed mentor that image and form has same class. Image is getting altered. She said that is fine for now, just view in mobile mode. 360×640 is what we need now and in that dimension image is not visible only !!!

**Comment by SnehaVeerakumar** [comment]
> * Check when user logins in there are many faults.
> * Check for the small screen the nav-bar is not responsive now we prefer `360-640`px.
> * More details button text by default white would look better.

Mentor asks for 360*640 whereas project admin views in laptop. Well organized, right?

**Comment by SnehaVeerakumar** [comment]
Do you think having same class for image, login form,signup form will have 4 different functionalities ?

**Comment by SnehaVeerakumar** [comment]
> Do you think having same class for image, login form,signup form will have 4 different functionalities ?

That sounds unreal.

**Comment by maneprajakta** [comment]
> > * Check when user logins in there are many faults.
> > * Check for the small screen the nav-bar is not responsive now we prefer `360-640`px.
> > * More details button text by default white would look better.
> 
> Mentor asks for 360*640 whereas project admin views in laptop. Well organized, right?

Just Some last comments from our side 
1. If you could read it carefully what is asked in the review I am talking about `nav-bar` it's not responsive why because the moon logo was added that comes under this PR.
2. Sorry to say you don't try to understand what the other side person is saying read carefully every PR review what we are asking you to do we are even adding ss for that what we mean.
3. Most important you are stuck on login page alignment let us assume it's our fault then also there are so many normal css fixes for dark mode.
It's for the first time we have come acrossed such a participant.
I don't know but this is how we work and till today no participant had any issue with it and everything was going peacefully.
No further comments from @Praful932 and my side!
It was nice you showed interest in our project just assume it's was a new learning for you whatever you feel and move on no further comments we expect. After all it's open-source !
Keep on Hacking!
PS: I feel to add this : just once go through the way you are putting your point to us such things are not entertained by anyone.

**Comment by Praful932** [comment]
>Mentor asks for 360*640 whereas project admin views in laptop. Well organized, right?

So if the maintainers see a bug in the PR, they ignore it?
Every maintainer can review and flag concerns in the PR before it gets approved. 
It's a step by step process, you fix one at a time, not all in one shot and the PR gets merged. Have some patience.
It's unfortunate to see such behaviour in open source. Good luck with your future endeavours in open source.

Locking this conversation.

**Pull request closed without merging**
