### PR TITLE
Placed the books side by side in Library page. 

### LINKED ISSUE #145: Arrange books side by side in Library
**Is your feature request related to a problem? Please describe.**
On the library page, each book is taking a large space and the user will have to scroll more. So we can align books in a different manner. 

**Describe the solution you'd like**
we can display 2 books side by side. 

**Are you willing to contribute to this issue?** [Yes/No]
Yes

I am a GSSOC'21 participant I would like to contribute to this issue.

### PR DESCRIPTION
**Pull request by nidhivanjare**
## Description
- The books in the Library Page are now sided by side placed. 
- Arrange books side by side in Library
- Fixes #145 

Before            |  After
:-------------------------:|:-------------------------:
  |  

Small Screen View            |  
:-------------------------:|

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by Praful932** [comment]
@nidhivanjare On 100% zoom it looks the same on my side, check out the deployment
image

**Review by maneprajakta — CHANGES_REQUESTED** [review]
Also for small screen book cards are not aligned to center.

**Comment by nidhivanjare** [comment]
Yes I have tried to fix the issue of zoom 

This is what it looks like now
Zoomed out            |  Zoomed In
:-------------------------:|:-------------------------:
  |  


Small screen view :
Screenshot 2021-04-03 at 4 00 27 PM

**Comment by maneprajakta** [comment]
@nidhivanjare have you committed the changes check [here](https://kitabe-pipeline-pr-164.herokuapp.com/) can't see the changes .

**Comment by nidhivanjare** [comment]
Hey, Sorry I didn't understand what are saying. 
Can you please explain what have I done wrong?

**Comment by maneprajakta** [comment]
> Hey, Sorry I didn't understand what are saying.
> Can you please explain what have I done wrong?

Ya so as per ss attached by you the cards are side by side right but we have deployed your PR
this is what we see at our end.

Screenshot from 2021-04-04 10-26-09

**Comment by Praful932** [comment]
@nidhivanjare Also the cards seem to have uneven sizes

**Review by Praful932 — CHANGES_REQUESTED** [review]
@nidhivanjare Also the cards seem to have uneven sizes

**Comment by nidhivanjare** [comment]
I have tried few Things 
But the difference in the card size is due to the length of the title of the book.
So whenever we zoom in the title text increases and accordingly the card size also increases to accommodate the title.

**Comment by Praful932** [comment]
Hi @nidhivanjare It is fine for the books to be a single column in responsive mode when two cannot fit, everything goes haywire else, on bigger screens you can stack side by side same as how the master branch displays for a single row

**Pull request closed without merging**
