### PR TITLE
Making UI changes for the search box

### PR DESCRIPTION
**Pull request by kulendu**
## Description
- List out your changes : 
   There are overall two UI changes I have made for the search box, they are as follows :
   1.  Increasing the **border-radius** of the search box, which in result will look more minimal and goes well with the theme.
   2. Secondly, making the search box move towards the right side of the top bar, close to the other tab section.
- Link the Issue which this resolves: #168 

## Affected Dependencies : 
No dependencies were affected during my code changes.

## How has this been tested?
This has been tested by using **flake8-django**. This is a plugin used to detect bad practices on Django projects. And also we  have used a file for checking the test cases (**manage.py test**) and successfully it has passed all the mentioned test cases.

Annotation 2021-04-02 232717

## GIF Before
Annotation 2021-04-01 184233

## GIF After
Annotation 2021-04-01 184416

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by Praful932 — CHANGES_REQUESTED** [review]
Unstage `settings.py`

**Comment by kulendu** [comment]
> Unstage `settings.py`

So should I make it s it was by default??

**Comment by Praful932** [comment]
> > Unstage `settings.py`
> 
> So should I make it s it was by default??
Yes
Run [this](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)

**Comment by kulendu** [comment]
Ok..... Thnk you

**Comment by kulendu** [comment]
But @Praful932 for running the server live I had made the changes according to the CONTRIBUTION.md file

**Comment by Praful932** [comment]
> But @Praful932 for running the server live I had made the changes according to the CONTRIBUTION.md file

That is for the dev environment. It is mentioned in the same file to **only stage necessary files.**

**Comment by kulendu** [comment]
Hey @Praful932 Im having some conflicts while removing files from the PR. So I'm closing the PR, and making a new one

**Pull request closed without merging**
