### PR TITLE
updated docstrings

### PR DESCRIPTION
**Pull request by vermatanu**
## Description
- changed single quotes to double quotes 
- removed indentation, used numpy style guide
- described some functions in detail
- issue #36 

## Affected Dependencies
helpers.py

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

## Checklist
- [ *] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ *] My changes do not edit/add any unrequired files.
- [ *] My changes are covered by tests.

### CODE REVIEW

**Review by Praful932 — COMMENTED** [review]
@vermatanu Tests are seeming to fail and I don't think you followed numpy docs guidelines 😬
Check [this](https://github.com/Praful932/Tf-Rec/blob/main/tfrec/utils/model_utils.py) sample file, how docstrings are written.

**Review by Praful932 — CHANGES_REQUESTED** [review]
@vermatanu Tests are seeming to fail and I don't think you followed numpy docs guidelines 😬
Check [this](https://github.com/Praful932/Tf-Rec/blob/main/tfrec/utils/model_utils.py) sample file, how docstrings are written.

**Comment by vermatanu** [comment]
@Praful932 is it okay if i take some time for this? i have my mid-sems going on😓

**Comment by Praful932** [comment]
@vermatanu I'll unassign you for now, you can take this up once you're free :)

**Pull request closed without merging**
