### PR TITLE
404 added in html

### PR DESCRIPTION
**Pull request by ShambhaviSharma0110**
## Description
- I have added 2 files, html and css for 404 page

## Affected Dependencies
mainpage
## How has this been tested?
works when ran live
## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA
- N/A

## GIF After
image

## Checklist
- [ x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ x] My changes do not edit/add any unrequired files.
- [x ] My changes are covered by tests.
additional remarks I made the whole thing in react.js if you'd like I'll create a pr for that as well...

### CODE REVIEW

**Review by Praful932 — CHANGES_REQUESTED** [review]
@ShambhaviSharma0110 Please update the PR description with relevant details

**Comment by Praful932** [comment]
@ShambhaviSharma0110 Any updates?

**Comment by ShambhaviSharma0110** [comment]
I updated no...? Do you want it in react.js as well?

**Comment by maneprajakta** [comment]
> @ShambhaviSharma0110 Please update the PR description with relevant details

@ShambhaviSharma0110 this ?

**Comment by ShambhaviSharma0110** [comment]
> > @ShambhaviSharma0110 Please update the PR description with relevant details
> 
> @ShambhaviSharma0110 this ?

updated

**Review by Praful932 — CHANGES_REQUESTED** [review]
@ShambhaviSharma0110 This is not what was discussed, please check the conversation on issue and make changes

**Comment by ShambhaviSharma0110** [comment]
> @ShambhaviSharma0110 This is not what was discussed, please check the conversation on issue and make changes

I can't run the website so idk what the theme looks like if you send me the wireframe I'll make UI changes...

**Comment by Praful932** [comment]
> > @ShambhaviSharma0110 This is not what was discussed, please check the conversation on issue and make changes
> 
> I can't run the website so idk what the theme looks like if you send me the wireframe I'll make UI changes...

You can check out the deployed website, see the issue comments for links

**Comment by arpit456jain** [comment]
Can I give it a try I am a gssoc'21 participant

**Comment by Praful932** [comment]
> Can I give it a try I am a gssoc'21 participant

Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42), it will help you get started with the project

**Comment by arpit456jain** [comment]
> > Can I give it a try I am a gssoc'21 participant
> 
> Check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42), it will help you get started with the project

Yes sir i had already read them once previously.
Just 1 doubt
Should i have to make the page from scratch or i can take a some normal 404 page free template and enhance it.

**Comment by Praful932** [comment]
@ShambhaviSharma0110 Any updates?

**Comment by maneprajakta** [comment]
@ShambhaviSharma0110 are you working on this ?

**Comment by arpit456jain** [comment]
> @ShambhaviSharma0110 are you working on this ?

@maneprajakta I want to give it a try I am a gssoc'21 participant.

**Comment by maneprajakta** [comment]
@arpit456jain okay you can take this issue.

**Comment by maneprajakta** [comment]
No updates received closing the PR

**Pull request closed without merging**
