### PR TITLE
UI  Enhancement of Login & Signup page

### LINKED ISSUE #194: Login and Signup Page Layout
**Describe the bug**
- For large screen :
   In `login in` page When a user enters wrong password space between buttons increases and also form content goes out of div.
- For small screen :
  On `login in` ,`sign up` page form border is not aligned properly also when a user enters wrong password  it's messed up same 
   as in large screen.

**To Reproduce**
- First bug:
1. Go to 'login'
2. Enter user name and wrong password
3. See error
- Second bug:
1. Open sigin & signup page on mobile.

**Expected behavior**
- For large screen: 
  Space btw buttons should not increase the form border should remain inside div
- For small screen:
  It should be responsive.

**Screenshots**
- Large screen:

Screenshot from 2021-04-11 21-52-16

- Small screen:
- `login page`
WhatsApp Image 2021-04-11 at 9 27 18 PM (1)

-`sign up page`
WhatsApp Image 2021-04-11 at 9 27 18 PM (3)

- `login with wrong password`
WhatsApp Image 2021-04-11 at 9 27 17 PM (1)

**Are you willing to contribute to this issue?** [Yes/No]
No
**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

### PR DESCRIPTION
**Pull request by satcasm**
## Description
- Improved the UI for login/signup on small and large screens
- Improved indentation in the required files
- Fixes #194 

## Affected Dependencies
NA

## How has this been tested?
```python manage.py test```

## GIF Before
before5

## GIF After
after3

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Check this Once
Screenshot from 2021-04-18 09-08-16

**Comment by satcasm** [comment]
Hey @maneprajakta done the changes.
image

**Review by maneprajakta — CHANGES_REQUESTED** [review]
For small screen 
- On the login page, the `welcome back` heading of the form is fixed check by opening the drop down.
- Also could you reduce this space for both  `login` and `Signup` page.
Screenshot from 2021-04-18 18-27-52

**Comment by satcasm** [comment]
@maneprajakta is this fine for signup?
image

**Comment by maneprajakta** [comment]
@satcasm Okays seems good!

**Comment by Praful932** [comment]
It seems there's still issues with signup for normal screens

**Comment by satcasm** [comment]
@Praful932 can you maybe describe it?

**Comment by Praful932** [comment]
This ones
image
image

**Comment by satcasm** [comment]
Ohh my bad didn't knew there were error messages during  singup too.

**Comment by satcasm** [comment]
Hey @Praful932 , now it is responsive with the error messages but we have to deal with the vacant space when no error is popped, otherwise it would mess up the box.

**Comment by Praful932** [comment]
Could you check the deployment? It still seems the same to me
image

**Comment by satcasm** [comment]
Hey @Praful932 have a look again , seems to work fine on my system and I checked the latest deployment too.
new

**Comment by Praful932** [comment]
I think this problem is of the difference in resolution.
Could you check these size - `1366 by 768` & `360 by 640`

**Comment by satcasm** [comment]
@Praful932 for ```360 by 640``` , we can't do much if we are going to follow the same layout, we have to either more the errors out of the box or something like that otherwise , just by playing with margin we can't accommodate all the errors.
image
```1366 by 768``` can be fixed but for ```360 by 640``` we might have to change the layout.

**Comment by Praful932** [comment]
Yes! That would be feasible, just make sure to reduce it only for mobile screens

**Comment by maneprajakta** [comment]
@satcasm any updates?

**Comment by satcasm** [comment]
@maneprajakta , apologies for the delay had some personal stuff to do will surely work on it in a day or two.

**Comment by satcasm** [comment]
Hey @Praful932 , made the changes have a look.
Thanks!

**Comment by Praful932** [comment]
image

**Comment by satcasm** [comment]
@Praful932 my bad there was a typo, fixed it.

**Review by maneprajakta — COMMENTED** [review]
Update Your Fork.

**Review by Praful932 — CHANGES_REQUESTED** [review]
It's bugged now for `1366 & 768` :/
image

**Comment by satcasm** [comment]
@Praful932 I have checked with all dimensions at 100%. Have a look .
Hope it's final ;)
Thanks!

**Review by maneprajakta — COMMENTED** [review]
Update your fork it's behind master.

**Comment by satcasm** [comment]
> Update your fork it's behind master.

The ```master``` branch of my fork it up to date with the original ```master``` branch.
Do I need to update for the current branch too?

**Comment by satcasm** [comment]
@maneprajakta Done!

**Review by maneprajakta — COMMENTED** [review]
At bottom, some gap between form border and button should be there.
Screenshot from 2021-05-07 10-22-13

**Comment by satcasm** [comment]
@maneprajakta , the thing is that if I give a gap it will mess up when error is thrown:
image
If you still want me to add some gap, we would have to reduce the margin-top of signup button (but then it wouldn't look good when no error is there) or we can reduce the padding of ```Sign up with Google``` button (again it won't look good as  screen would be large). Let me know what you think.

**Comment by satcasm** [comment]
@maneprajakta So is there anything else you want me to do?

**Review by maneprajakta — APPROVED** [review]
Good to go!

**Review by Praful932 — APPROVED** [review]
Nice work!

**Pull request merged**
