### PR TITLE
Hyperparameter Tuning

### LINKED ISSUE #39: Better Hyperparameter Search
**Is your feature request related to a problem? Please describe.**
Currently the number of components used to determine book embedding is `200`. Since it seemed to work and the search takes a lot of time for us locally, We fixed the hyperparameter to that.

**Describe the solution you'd like**
Does a better hyperaparameter exist? Can we do a Randomized Search or a Grid Search to determine that, maybe even tune other parameters? Even after finding a better one with a lesser loss, does it produce a better output when the similarity metric is used?

**Additional context**
Refer the Embedding Notebook in The Notebook & Files Section for code. You can either Integrate Surprise with ScikitLearn Grid Search or use [another ](https://github.com/Praful932/Tf-Rec) package to determine embedding and do they perform well

### PR DESCRIPTION
**Pull request by Aditi0102**
## Description
- Added SVD Model 
- Link for the collab file: https://colab.research.google.com/drive/1wTMVKl4YIDgPUXU3b8ar-QpunlG-mfQ4?usp=sharing
- Fixes #39 

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [X] My changes do not edit/add any unrequired files.
- [X] My changes are covered by tests.

### CODE REVIEW

**Comment by Aditi0102** [comment]
@Praful932 I have added SVD Model. Please check it and let me know if any changes are required.

**Comment by maneprajakta** [comment]
@Aditi0102 can't see tuning for hyperparameters done in notebook.

**Comment by Praful932** [comment]
Add a [Google Collab](https://colab.research.google.com/) link to the notebook in the PR description so we can review and compare the performance

**Comment by Aditi0102** [comment]
@Praful932 I have added the link. Please also tell me any required changes to be done.

**Comment by Praful932** [comment]
Same, I couldn't see any tuning in there?

**Comment by maneprajakta** [comment]
@Aditi0102 is there anything else that you have got to show us?

**Comment by maneprajakta** [comment]
No updates

**Pull request closed without merging**
