### PR TITLE
⚒️[Fix]: added rated books side by side

### PR DESCRIPTION
**Pull request by maneprajakta**
## Description
- In Rated books page added books side by side
- Also formatted the code.

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by Praful932** [comment]
New merge caused conflicts 👀

**Comment by maneprajakta** [comment]
Not getting why this happend.

**Comment by Praful932** [comment]
Try pushing to this branch again

**Comment by maneprajakta** [comment]
The changes done from this branch are already merged in master.

**Comment by maneprajakta** [comment]
I will close this.

**Pull request closed without merging**
