### PR TITLE
Added Preloader

### LINKED ISSUE #43: Preloader 💫
**Is your feature request related to a problem? Please describe.**
Since the project is hosted on the heroku free tier, it takes some time to load, It would be nice to have a preloader.

**Describe the solution you'd like**
Before the homepage is loaded, there should be a loading animation whose design matches with the theme of the website. It should load only once(using cookies) when it enters through the domain name, and not everytime the user goes to the homepage.

- First a mockup design should be shown
- Then after approval code changes should be made

**Describe alternatives you've considered**
Open to alternatives!

**Additional context**
The preloader should be responsive and bug-free.

### PR DESCRIPTION
**Pull request by cryptofox17**
## Description
- Added the Preloader
- Fixes #43 

## Affected Dependencies
NA

## How has this been tested?
Ran it on local server

## GIF Before
before_preloader

## GIF After
after_preloader

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
Preloader now loads earlier.
But it loads even when clicked on `Home` in nav-bar and `navbar brand`.

**Comment by cryptofox17** [comment]
@maneprajakta you can have a look at my code I have ensured that it cookie exists then the preloader container should be hidden. But it takes time to execute that's why it appears for a bit. The cookie is generated but it takes time to check it.
I even tried putting it in layout.html and even keeping the script tag at the top but it doesn't make any change. I also tried checking online but couldn't find anything. So I'm unsure what to do. Any help would be much appreciated

**Comment by Praful932** [comment]
@cryptofox17 Is it the same when running locally? Could you try delaying the preloader?

**Comment by cryptofox17** [comment]
@Praful932 yes it runs fine like shown in the gifs. Maybe it blinks for a second before hiding, but it definitely not as long as how it happens in the deployed site. I tried delaying it too but it delays it later so it doesn't appear on the right time.

**Comment by Praful932** [comment]
The cookie is being checked later, it would be a bit annoying if user goes back to the homepage since it takes around 1-2 second to finish the loading even after showing for the first time

**Comment by cryptofox17** [comment]
@Praful932 yeah, I understand. Someone told me I could try using XMLHttps requests to do it but I have never used it before and I'm unsure if that would work. 
If you have any suggestions on how I can fix this issue please let me know

**Comment by Praful932** [comment]
@cryptofox17 Check [this](https://stackoverflow.com/questions/244183/how-to-display-a-loading-screen-while-site-content-loads)  and [this](https://icons8.com/preloaders/en/ajax_loader_script), If you need more help reach out in project channel on discord

**Comment by cryptofox17** [comment]
@Praful932 thank you for the resources, I will look into it and make the necessary changes. Possibly by tomorrow or the day after

**Comment by maneprajakta** [comment]
@Praful932 what you say ?

**Comment by Praful932** [comment]
@cryptofox17 From the ones that you tried, is this the best one that's performing well enough on deployment?
Also the timeout is 0.5 sec, so it's the heroku which is slowing it down I guess compared to local?

**Comment by cryptofox17** [comment]
@Praful932 , yes this one is the best one. The previous one was showing the preloader much later after loading. 
And after making this PR, I tried using XMLHTTPS request, local storage etc to try but none of them made any change so I just discarded them. 
I have kept the preloader to display for around 700ms, it shows it for much shorter amount of time on local than on the actual deployment.

**Review by Praful932 — APPROVED** [review]
Nice work 🚀

**Review by maneprajakta — APPROVED** [review]
Great Work :star2:

**Comment by cryptofox17** [comment]
Thank you :)

**Pull request merged**
