### PR TITLE
Adding description to find similar books

### LINKED ISSUE #129: Using description to find similar books
**Is your feature request related to a problem? Please describe.**
It's not a problem . I just think that titles and genres provide a foundation for the recommendation system and description of a book can be added as a feature that also determines if other books are similar

**Describe the solution you'd like**
I'd like to implement a cosine similarity using book descriptions/plots to make the system more accurate  

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
No I have none as of now.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by knmehta12**
## Description
- List out your changes
I created a column named cleaned_desc in the already existing dataset and reformatted the model with an extra feature.
As directed, I uploaded a CSV file with book description in it. And the link to colab notebook.
- [Collab Link](https://colab.research.google.com/drive/1tFbXkkMrYrDfWHU2F6tnMucRXC4zqoxy?usp=sharing#scrollTo=nq92a9ZGeEiO)
- Fixes #129 

## How has this been tested?
It has been tested on books of different genres and in various languages. It gives relevant recommendations for almost all of them.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — COMMENTED** [review]
drop `Unnamed: 0.1` column from CSV file.

**Comment by knmehta12** [comment]
Hi, do you mean `Unnamed 0`. That's the column I see? And there'd another column that has empty name.

**Comment by Praful932** [comment]
Yes that's the one

**Comment by knmehta12** [comment]
I did that. Tell me if any more changes are required. :)

**Review by maneprajakta — COMMENTED** [review]
All seems great to me.
Replace `cosin_rating_sim.npz` with the new one.
@Praful932 what you say on how we got the book description?

**Comment by Praful932** [comment]
> All seems great to me.
> Replace `cosin_rating_sim.npz` with the new one.
> @Praful932 what you say on how we got the book description?

Book description as in? Didn't get you

@knmehta12 Shouldn't the description be separated by space since Tfidf is used here?

**Comment by knmehta12** [comment]
> > All seems great to me.
> > Replace `cosin_rating_sim.npz` with the new one.
> > @Praful932 what you say on how we got the book description?
> 
> Book description as in? Didn't get you
> 
> @knmehta12 Shouldn't the description be separated by space since Tfidf is used here?

I wanted to do that but didn't see a significant change in results. I can remove that function that removes space. Should I?

**Comment by Praful932** [comment]
We'll check & revert back :)

**Comment by knmehta12** [comment]
Sure let me know if I should make any changes. Thank you.

**Comment by maneprajakta** [comment]
> > All seems great to me.
> > Replace `cosin_rating_sim.npz` with the new one.
> > @Praful932 what you say on how we got the book description?
> 
> Book description as in? Didn't get you
> 
> @knmehta12 Shouldn't the description be separated by space since Tfidf is used here?

@Praful932 
Ya, I mean how we got the book description column filled up.

**Comment by Praful932** [comment]
Since the scraping, I think we can have the raw desc itself,
@knmehta12 Could you add the original description in the collab & the csv file, and show the cleaning & processing steps in the notebook till how it is now

**Comment by knmehta12** [comment]
Sure. Should I link the collab here in comments? It's just removing non-ascii and punctuation characters.

**Comment by Praful932** [comment]
> Sure. Should I link the collab here in comments? It's just removing non-ascii and punctuation characters.

You can add the code in the same collab that you shared? (Link in PR Description)

**Comment by Praful932** [comment]
> Sure. Then I'll add `desc.csv`?? Or just show you the cleaning in comments?

- The current dataset that you uploaded change the `desc` column to raw(the one you scraped) which is not cleaned 
- Add the cleaning in the notebook itself that you shared using this dataset
Let me know if there are any more doubts

**Comment by knmehta12** [comment]
Okay sure. Will do. :)

**Comment by knmehta12** [comment]
Hello. Is it okay if I remove that function that removes space and converts all words to lower?

**Comment by Praful932** [comment]
> Hello. Is it okay if I remove that function that removes space and converts all words to lower?

Keep it for now, we'll review and add any modifications as necessary

**Comment by knmehta12** [comment]
Hi. Do I need to change anything more?

**Comment by Praful932** [comment]
Nope, as of rn, We'll go through the collab & revert back :)

**Comment by Praful932** [comment]
@knmehta12 To confirm, There are no such cases tho right?
image

**Comment by knmehta12** [comment]
> @knmehta12 To confirm, There are no such cases tho right?
> image

No there are. About 37. I don't remember the exact figure. Should I fill them manually?

**Comment by Praful932** [comment]
Could you show which ones, I found None that's why

**Comment by knmehta12** [comment]
Well I just checked and yes there are none. I'm surprised myself. I ran it once when I imported cleaned description and there were some empty values.

**Comment by knmehta12** [comment]
I couldn't find them either. I ran it once before when I imported cleaned description and it said there were empty values. 😯

**Comment by Praful932** [comment]
@knmehta12 
Replace the current model sim file with [this](https://drive.google.com/file/d/11FW0Vu_K5-o6KkwLnqBarAg1usbLOCm8/view?usp=sharing)

**Comment by knmehta12** [comment]
How can I do that? Git doesn't let me upload a large file.

**Comment by Praful932** [comment]
@knmehta12 Check out git lfs, push using that

**Comment by knmehta12** [comment]
Hi. I uploaded the file. Please let me know if I need to change anything else. Thank you :)

**Comment by Praful932** [comment]
@knmehta12 Could you add a `app.json` file in root with the following content
```
{
  "buildpacks": [
    {
      "url": "https://github.com/raxod502/heroku-buildpack-git-lfs"
    },
    {
      "url": "heroku/python"
    }
  ]
}
```

**Comment by knmehta12** [comment]
Sure. What location is is supposed to be in?

**Comment by Praful932** [comment]
Hi @knmehta12 Due to the large size of the similarity file and the limit of [heroku slug size](https://help.heroku.com/KUFMEES1/my-slug-size-is-too-large-how-can-i-make-it-smaller#:~:text=Slugs%20on%20Heroku%20consist%20of,allowed%20slug%20size%20is%20500MB.) on the free tier, there have been several issues with deploying.
- Current slug size including the big file is `371 MB`
- Unfortuantely even if the slug is < 500 MB, the git lfs extension of heroku downloads all the file that are in my git lfs storage making it a slug of > ~600 MB, and git lfs even currently does [not have a way of freeing the space](https://stackoverflow.com/questions/34579211/how-to-delete-a-file-tracked-by-git-lfs-and-release-the-storage-quota), even if the file is deleted from the repo, the heroku extension downloads lfs files directly from git lfs storage.

Another solution that we would like to explore is downloading the file directly on the go which is hosted on gdrive.
We would like you to remove all the changes except changes to `README.md` and `books.cv` also including deleting the similarity files.
We would like to test out how the application performs if the file is downloaded on the go(we will do the changes). If it is equivalent to what it was earlier with no other issues, we would be happy to merge :)

**Comment by knmehta12** [comment]
Okay sure, I'll remove the file. Thank you.

**Comment by knmehta12** [comment]
Should I remove `cosin_rating_sim.npz`. Or replace it with the previous file?

**Comment by Praful932** [comment]
> Should I remove `cosin_rating_sim.npz`. Or replace it with the previous file?

No need of replacing, remove it too

**Comment by Praful932** [comment]
@knmehta12 Add `gdown` as a package, also freeze in the dependency file.
And add these three lines [here](https://github.com/Praful932/Kitabe/blob/master/mainapp/helpers.py#L13)
```python
url = 'https://drive.google.com/uc?id=11FW0Vu_K5-o6KkwLnqBarAg1usbLOCm8'
cosine_sim_path = os.path.join(settings.STATICFILES_DIRS[0] + '/mainapp/model_files/cv/cosine_rating_sim.npz')
if not os.path.exists(cosine_sim_path):
    gdown.download(url, cosine_sim_path, quiet=False) 
```

**Comment by knmehta12** [comment]
Hi I don't understand what you mean by _also freeze in the dependency file_ . Am I supposed to add a package called freeze? Thank you.

**Comment by Praful932** [comment]
Hi @knmehta12 just these lines :)
```
pip install gdown
pip freeze > requirements.txt
```

**Comment by Praful932** [comment]
Checks are failing :/

**Comment by knmehta12** [comment]
I tried to find why are the checks failing but I can't find the reason. What could it be?

**Comment by Praful932** [comment]
@knmehta12 Seems the slug size is becoming too large for heroku ~650 mb :/
The current file size of `cosine_sim` with description is too big 152 mb, try making it smaller

**Comment by knmehta12** [comment]
Hi. I tried searching but don't know how that will be possible. Do you have any ideas? Otherwise it's okay if you close this pr.

**Comment by Praful932** [comment]
> Hi. I tried searching but don't know how that will be possible. Do you have any ideas? Otherwise it's okay if you close this pr.

Optimized it a bit :)

**Comment by Praful932** [comment]
@knmehta12 Also could you update your fork

**Comment by Praful932** [comment]
@knmehta12 Due to limitations of the free tier storage on heroku, we are unable to deploy the similarity file, the work that you did is splendid and we will be definitely using it when we start building an api(currently in backlog) for model inference :)

**Review by maneprajakta — APPROVED** [review]

**Review by Praful932 — APPROVED** [review]

**Pull request merged**
