### PR TITLE
Front End Bugs Fixed

### PR DESCRIPTION
**Pull request by Aayu231**
## Description
Changes:
- Fixed home page button size and alignment.
- Fixed your read section improper size button, alignment and validation.
Issue: #30 

## Affected Dependencies
None

## How has this been tested?
Using ```flake8``` & ```python manage.py test```

Screenshot (1377)

## Before
before1

before2

## After

Screenshot (1373)

Screenshot (1375)

Screenshot (1376)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Check for small screen  `rate this button`:
Screenshot from 2021-04-11 11-30-52
- In Your Read Section Rating Validation is not done also both buttons should not be side by side . More details button is above rate this button we want both button to be centrally aligned.

**Comment by Praful932** [comment]
Also there's a responsive issue for `Your Read` Page

**Comment by maneprajakta** [comment]
@Aayu231 any updates?

**Comment by Aayu231** [comment]
I have unassigned myself from the issue

**Pull request closed without merging**
