### PR TITLE
Improved the book list layout of the explore page

### LINKED ISSUE #74: Better UI for book list in the explore page
**Describe the bug**
When you hover over any book displayed in the explore page, 2 buttons (More Details, Rate this book) appear below the book div. This causes all the divs under this block to be shifted downwards, which appears to be messy and confusing.

**To Reproduce**
1. Go to https://kitabe-app.herokuapp.com/
2. Click on the explore button in the top right corner
3. Hover over any book and see how it changes when you unhover. 

**Expected behavior**
We can keep the layout consistent and change the divs in the explore page so that they are similar to the book list appearing in any genre page. For example: https://kitabe-app.herokuapp.com/genre_books/Fantasy 

**Screenshots**
image

The buttons that have appeared under the first book make the page look messy.

It could be made similar to the books in genre list
image

**Are you willing to contribute to this issue?** 
Yes. I would like to contribute to this issue as a Gssoc'21 participant.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 89

**Smartphone (please complete the following information):**
 - Device: Redmi K20

**Additional context**

### PR DESCRIPTION
**Pull request by AmrutaKoshe**
## Description
- Changed the layout of the explore page to make it user friendly. Made it similar to the layout of the book-genre page.
- made changes in the files explore.html and explore.css
- closes #74 

Before:
image

After:
image

on small screens:
image

## How has this been tested?
Ran it in my localhost 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by maneprajakta** [comment]
@Praful932 I don't think we were expecting this.

**Comment by AmrutaKoshe** [comment]
> @Praful932 I don't think we were expecting this.

what were you expecting?

**Comment by maneprajakta** [comment]
> > @Praful932 I don't think we were expecting this.
> 
> what were you expecting?

A small misunderstanding from my side checked your Issue description this is what we were excepting :) .

**Comment by maneprajakta** [comment]
@AmrutaKoshe Could you attach the ss for small screens in PR template .

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe Could you attach the ss for small screens in PR template .

Yep done! 👍🏽

**Comment by maneprajakta** [comment]
@AmrutaKoshe 
For small screen :
- Card should be at the center 
- Also the gap between the button should be more
- Carousel should be there the same it was earlier there.

The font style of the book author should be the same as in genre.
Also 

Screenshot from 2021-03-15 14-18-35

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe
> For small screen :
> 
> * Card should be at the center
> * Also the gap between the button should be more
> * Carousel should be there the same it was earlier there.
> 
> The font style of the book author should be the same as in genre.
> Also
> 
> Screenshot from 2021-03-15 14-18-35

I have made the changes, but I did not understand what you mean by carousel? Also, the button gap seems sufficient as it is. Only when it is hovered, it expands

**Review by Praful932 — CHANGES_REQUESTED** [review]
Update your fork, there are some conflicts

**Comment by maneprajakta** [comment]
@AmrutaKoshe 
- For the small screen, we had a carousel [check this](https://github.com/Praful932/Kitabe/blob/78a88a15a3bb245a551be9f51d69903a09db607c/templates/mainapp/explore.html#L55) 3 carousels 50 books each.
- Shift rate this button a bit left open hover so that it does not collapse with more details button.

**Comment by Praful932** [comment]
@AmrutaKoshe Update your branch with the latest master

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe
> 
> * For the small screen, we had a carousel [check this](https://github.com/Praful932/Kitabe/blob/78a88a15a3bb245a551be9f51d69903a09db607c/templates/mainapp/explore.html#L55) 3 carousels 50 books each.
> * Shift rate this button a bit left open hover so that it does not collapse with more details button.

The carousel is still there.... I haven't made any changes to that 🤔

Also, when we hover over the "rate this book" button, the button gets expanded. So I was thinking the 5 stars can be displayed inside the button itself without making the button bigger. But I am not able to find the code where the button gets enlarged.

**Comment by maneprajakta** [comment]
@AmrutaKoshe we have deployed your PR [check this](https://kitabe-pipeline-pr-94.herokuapp.com/) for small screen in explore section we have carousel [like this](https://kitabe-app.herokuapp.com/explore_books/).
Plz, add a gif of it if you can see it locally.

We have added transition to the button. Let it be same [Line](https://github.com/Praful932/Kitabe/blob/78a88a15a3bb245a551be9f51d69903a09db607c/static/mainapp/css/explore.css#L71) for the effect.

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe we have deployed your PR [check this](https://kitabe-pipeline-pr-94.herokuapp.com/) for small screen in explore section we have carousel [like this](https://kitabe-app.herokuapp.com/explore_books/).
> Plz, add a gif of it if you can see it locally.
> 
> We have added transition to the button. Let it be same [Line](https://github.com/Praful932/Kitabe/blob/78a88a15a3bb245a551be9f51d69903a09db607c/static/mainapp/css/explore.css#L71) for the effect.

yes okay understood! Is the carousel issue fixed now? I am once again not able to view the changes in my localhost 🤦🏽‍♀️

**Review by Praful932 — CHANGES_REQUESTED** [review]
When the explore page is visited everything is becoming unclickable

Also there seem some extra commits in your PR

**Comment by AmrutaKoshe** [comment]
> When the explore page is visited everything is becoming unclickable
> 
> Also there seem some extra commits in your PR

I am able to click on items in the explore page 🤔 even in the deployment. 
Also, which extra commits are you talking about?

**Review by maneprajakta — CHANGES_REQUESTED** [review]
@AmrutaKoshe 
- Total of 11 commits are coming from your PR
- Also for large screen carousel is not there + buttons are overlapping.
- For small screens nothing is clickable.

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe
> 
> * Total of 11 commits are coming from your PR
> * Also for large screen carousel is not there + buttons are overlapping.
> * For small screens nothing is clickable.

- I have made 6 commits to this PR..... so what do I have to do for it?
- Large screens don't need carousel right? Even in the current master, there's no carousel for large screen [here](https://kitabe-app.herokuapp.com/explore_books/)
- I am able to click on items in small screens in my deployment 🤔-
explorePage

**Comment by Praful932** [comment]
> When the explore page is visited everything is becoming unclickable
> 
> Also there seem some extra commits in your PR

@AmrutaKoshe Works now for some reason, although issue is there in small screens, you can remove the carousel in large screens
also there are 11 commits in your PR

**Comment by AmrutaKoshe** [comment]
> > When the explore page is visited everything is becoming unclickable
> > Also there seem some extra commits in your PR
> 
> @AmrutaKoshe Works now for some reason, although issue is there in small screens, you can remove the carousel in large screens
> also there are 11 commits in your PR

Okay. But can you tell what am I supposed to do about the 11 commits ? The first five commits are not mine
image
Do I remove it? If yes, then how?

**Comment by Praful932** [comment]
@AmrutaKoshe Not sure why this happened,
1. Update your fork's master
2. Take Backup of your changes/soft reset your head to your first commit and stash your changes
3. Branch out a fresh branch off master.
4. Paste/Pop your changes 
5. Make a new PR

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe Not sure why this happened,
> Try force pushing to this branch if the commits still not disappear follow these steps
> 
> 1. Update your fork's master
> 2. Take Backup of your changes/soft reset your head to your first commit and stash your changes
> 3. Branch out a fresh branch off master.
> 4. Paste/Pop your changes
> 5. Make a new PR

Can I revert the first five commits?

**Comment by Praful932** [comment]
> > @AmrutaKoshe Not sure why this happened,
> > Try force pushing to this branch if the commits still not disappear follow these steps
> > 
> > 1. Update your fork's master
> > 2. Take Backup of your changes/soft reset your head to your first commit and stash your changes
> > 3. Branch out a fresh branch off master.
> > 4. Paste/Pop your changes
> > 5. Make a new PR
> 
> Can I revert the first five commits?

It would mess up the commit history, better to close this PR and make a new one, if the issue persists

**Comment by AmrutaKoshe** [comment]
> > > @AmrutaKoshe Not sure why this happened,
> > > Try force pushing to this branch if the commits still not disappear follow these steps
> > > 
> > > 1. Update your fork's master
> > > 2. Take Backup of your changes/soft reset your head to your first commit and stash your changes
> > > 3. Branch out a fresh branch off master.
> > > 4. Paste/Pop your changes
> > > 5. Make a new PR
> > 
> > 
> > Can I revert the first five commits?
> 
> It would mess up the commit history, better to close this PR and make a new one, if the issue persists


> > > @AmrutaKoshe Not sure why this happened,
> > > Try force pushing to this branch if the commits still not disappear follow these steps
> > > 
> > > 1. Update your fork's master
> > > 2. Take Backup of your changes/soft reset your head to your first commit and stash your changes
> > > 3. Branch out a fresh branch off master.
> > > 4. Paste/Pop your changes
> > > 5. Make a new PR
> > 
> > 
> > Can I revert the first five commits?
> 
> It would mess up the commit history, better to close this PR and make a new one, if the issue persists

oh okay! But I am genuinely asking, why do we have a problem with the first five commits?

**Comment by Praful932** [comment]
Because we already have those commits in master :)
And we don't want old commits to be duplicated with any PR
image

**Comment by AmrutaKoshe** [comment]
> Because we already have those commits in master :)
> And we don't want old commits to be duplicated with any PR
> image



> Because we already have those commits in master :)
> And we don't want old commits to be duplicated with any PR
> image

force push doesn't work - it says everything is up to date, so I'll create a new PR.

**Pull request closed without merging**
