### PR TITLE
Align Popular Among Us Book Cards

### LINKED ISSUE #229: Improper positioning
**Is your feature request related to a problem? Please describe.**
On the main page, the tiles are in quite an improper position. 

**Describe the solution you'd like**
Aligning all tiles to the same baseline.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Additional context**
Screenshot from 2021-05-11 16-32-40

### PR DESCRIPTION
**Pull request by sonaljain067**
## Description
- Fixing the height of the carousel to make it uniform
- Fixes #229 

## Affected Dependencies
NA

## How has this been tested?
`python manage.py test`

## GIF Before
book_card_before

## GIF After
book_card_after

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [X] My changes do not edit/add any unrequired files.
- [X] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — COMMENTED** [review]
Could you check for `360x640`px
Screenshot from 2021-05-13 20-25-46

**Comment by sonaljain067** [comment]
> Could you check for `360x640`px
> Screenshot from 2021-05-13 20-25-46

Yes

**Review by maneprajakta — COMMENTED** [review]
LGTM :rocket:

**Review by Praful932 — CHANGES_REQUESTED** [review]
Changing this has affected the Genre Cards as well, keep it as it is in the original application
Your Changes
image

Current application
image

Also similarly on all screen widths

**Comment by sonaljain067** [comment]
> Changing this has affected the Genre Cards as well, keep it as it is in the original application
> Your Changes
> image
> 
> Current application
> image
> 
> Also similarly on all screen widths

Ok I would rectify it.

**Comment by sonaljain067** [comment]
Are there more modifications needed?

**Review by Praful932 — APPROVED** [review]
Looks fine to me, Nice work 🚀

**Review by maneprajakta — APPROVED** [review]

**Pull request merged**
