### PR TITLE
Sticky Navbar

### PR DESCRIPTION
**Pull request by padmajabhol**
## Description
- Fixed the navbar
- The navbar disappeared as we scrolled down.

## Affected Dependencies
None

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA
- NA

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

### CODE REVIEW

**Comment by Praful932** [comment]
@padmajabhol Awesome! You're almost there. Edit the PR template to add in all other details
- Before, after GIFs
- Which issue it fixes #44

**Comment by maneprajakta** [comment]
@padmajabhol Are you working on changes asked in PR description .

**Comment by maneprajakta** [comment]
@padmajabhol Are you working on changes asked in PR description .

**Comment by padmajabhol** [comment]
> @padmajabhol Are you working on changes asked in PR description .

No

**Pull request closed without merging**
