### PR TITLE
Fixed Blinking cursor on top of Search

### PR DESCRIPTION
**Pull request by kabilanvennila**
## Description

```diff
Layout.html
- &#xf002    Search for books
+ Search for books               &#xf002
```
```diff
Layout.css
-  width: 100%; 
+  width: 90%;
```

-  #256

## Affected Dependencies
None 

## How has this been tested?
```python manage.py test```

## GIF Before
- Before

## GIF After
- After
 
## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [X] My changes do not edit/add any unrequired files.
- [X] My changes are covered by tests.

### CODE REVIEW

**Review by maneprajakta — CHANGES_REQUESTED** [review]
- Keep the entire search bar length same ar earlier
Screenshot from 2021-11-12 17-22-37
Screenshot from 2021-11-12 17-22-42

**Comment by Praful932** [comment]
@kabilanvennila Ping

**Comment by Praful932** [comment]
@kabilanvennila Ping again

**Comment by Praful932** [comment]
closing this due to inactivity

**Pull request closed without merging**
