### PR TITLE
[WIP] Dark mode

### PR DESCRIPTION
**Pull request by SnehaVeerakumar**
## Description
- https://github.com/Praful932/Kitabe/issues/41
- Added dark-mode.
- Existing wireframe have been used with an additional of fa-moon-o icon to the right of logo.
- Added dark-mode.css to make necessary changes in UI for dark theme.
- Layout.html is configured to add icon and JavaScript for the functioning of dark theme toggle.
- Once dark-mode is turned on, dark theme will be applied until it is turned off. Refreshing the page, moving from one page to another will not affect the theme.

## Affected Dependencies
- None

## How has this been tested?
- By deploying in local server.

## Demo Video
- https://stdntpartners-my.sharepoint.com/:v:/g/personal/sneha_veerakumar_studentambassadors_com/EVazFbAmCCZCn0qbhX9nm5EBIrxqdV2sXZz9GwzulbF2dA?e=G20XNS
- NOTE : Delay in loading server  is becoz of local server. Once you deploy it, issue will be rectified.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ ] My changes do not edit/add any unrequired files.
- [ ] My changes are covered by tests.

### CODE REVIEW

**Comment by SnehaVeerakumar** [comment]
@Praful932  Kindly view the demo video and provide the feedback.

**Review by maneprajakta — CHANGES_REQUESTED** [review]
1. login/signup doesn't look good.
2. Explore page looks fine just make the book title bold a bit. 
3. In the Popular among users section black book card doesn't look good.
4. After changing to a dark theme the button should change from moon to sun.

**Comment by maneprajakta** [comment]
@SnehaVeerakumar Also after user logins in we have other pages too which are not shown in the video.

**Comment by SnehaVeerakumar** [comment]
I will update it by tomorrow.

**Comment by SnehaVeerakumar** [comment]
By inheriting existing light mode UI, this is the result. I would like to change the whole UI for dark mode if you approve.

**Comment by maneprajakta** [comment]
@Praful932 is it possible to deploy this PR so that we can keep on checking the changes done. What you say?

**Comment by Praful932** [comment]
> @Praful932 is it possible to deploy this PR so that we can keep on checking the changes done. What you say?

Sure

**Review by Praful932 — CHANGES_REQUESTED** [review]
There's some error which is causing internal server error when homepage is opened.

**Comment by SnehaVeerakumar** [comment]
> There's some error which is causing internal server error when homepage is opened.

I checked it now and it works fine in localhost. Please take care of the configurations for heroku app.

**Comment by Praful932** [comment]
Just made a fix, could you update your branch 
Thanks

**Comment by SnehaVeerakumar** [comment]
All done.

**Comment by maneprajakta** [comment]
any updates?

**Comment by SnehaVeerakumar** [comment]
> any updates?

Yeah, I will complete it by today.

**Comment by SnehaVeerakumar** [comment]
Due to deployment issues, adding a new PR #159

**Comment by SnehaVeerakumar** [comment]
Due to deployment issues, created a new PR #208

**Pull request closed without merging**
