### PR TITLE
Added search icon

### LINKED ISSUE #111: Adding a Search Icon in the Search bar
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problem. It's about making the page more attractive.

**Describe the solution you'd like**
I want to add a "Search Icon" in the "Search Bar" to give a better look to the project.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

**Describe alternatives you've considered**
As of now, I have no alternatives for this, I just want to add a "Search Icon" in the "Search Bar".

**Additional context**
Screenshot (2706)_LI

@maneprajakta I want to contribute this as a part of GSSOC'21.Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Sweeti-Gupta**
## Description
- Search Icon added 
- Fixed #111

## Affected Dependencies
N/A

## How has this been tested?
`python manage.py runserver`

## GIF Before
Kitabe_before

## GIF After
Kitabe_after2

`360*640` Resolution
Screenshot (2733)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

## Additional Context
@maneprajakta I have added the search icon, removed the unnecessary changes and created a new PR to resolve conflict. Please review it.

### CODE REVIEW

**Review by Praful932 — CHANGES_REQUESTED** [review]
@Sweeti-Gupta Attach ss in PR description for `360*640` resolution

**Comment by Sweeti-Gupta** [comment]
> @Sweeti-Gupta Attach ss in PR description for `360*640` resolution

Done!

**Comment by maneprajakta** [comment]
@Praful932 if you could deploy this?

**Comment by Praful932** [comment]
> @Praful932 if you could deploy this?

It's deployed

**Review by Praful932 — CHANGES_REQUESTED** [review]
image
In mobile view the `Search for books` seems to go to the right,
it would be nice to have the text to the direct right of the icon

**Comment by Sweeti-Gupta** [comment]
@Praful932  I have done the changes. Please review and merge it.

Screenshot (2736)

**Review by Praful932 — APPROVED** [review]

**Review by maneprajakta — APPROVED** [review]
Great Work :rocket:

**Pull request merged**
